name: 2DGS-W
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - ffmpeg=4.2.2
  - pillow=10.2.0
  - cudatoolkit=11.6
  - python=3.7.13
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - pip=22.3.1
  - typing_extensions=4.9.0
  - pip:
    - open3d==0.18.0
    - mediapy==1.1.2
    - scikit-image==0.21.0
    - tqdm==4.66.2
    - trimesh==4.3.2
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - imageio==2.31.2
    - imageio-ffmpeg==0.4.9
    - pandas==1.3.5
    - lpips==0.1.4
    - plyfile
    - matplotlib==3.5.3
    - kornia==0.6.8
    - importlib_metadata==6.7.0
    - opencv-python




